-- 코드를 작성해주세요
SELECT YEAR(A.DIFFERENTIATION_DATE) AS YEAR, (B.MAXC - A.SIZE_OF_COLONY) AS YEAR_DEV, A.ID
FROM ECOLI_DATA AS A
JOIN (SELECT MAX(SIZE_OF_COLONY) AS MAXC, YEAR(DIFFERENTIATION_DATE) AS YEAR
FROM ECOLI_DATA
GROUP BY YEAR(DIFFERENTIATION_DATE)) AS B
ON YEAR(A.DIFFERENTIATION_DATE) = B. YEAR
ORDER BY YEAR, YEAR_DEV ASC;